import { resolve } from 'node:path';
import { CATALOG, dependenciesFor } from './catalog.js';
import { validateConfig } from './config.js';
import type { ArchitectureConfig, ArchitecturePlan, PlannedFile, Presentation } from './types.js';

const marker = (title: string): string => `/** ${title}. Generated by rn-arch; replace the placeholder through the architecture skill. */\n`;

function moduleRoot(config: ArchitectureConfig, name: string): string {
  return config.topology === 'modular-monolith' ? `src/modules/${name}` : `packages/module-${name}/src`;
}

function presentationFolders(presentation: Presentation): string[] {
  if (presentation === 'hook-based-mvvm') return ['components', 'screens', 'hooks'];
  if (presentation === 'mvi') return ['components', 'screens', 'intent', 'state'];
  if (presentation === 'clean') return ['presentation', 'domain', 'data'];
  return ['view', 'interactor', 'presenter', 'entity', 'router'];
}

function add(files: PlannedFile[], path: string, content: string, reason: string): void {
  files.push({ path, content, reason });
}

export function plan(rootInput: string, config: ArchitectureConfig): ArchitecturePlan {
  const files: PlannedFile[] = [];
  const warnings = validateConfig(config);
  add(files, 'rn-arch.config.json', `${JSON.stringify(config, null, 2)}\n`, 'Persistent architecture contract');
  add(files, 'docs/architecture/README.md', '# Architecture decisions\n\nRecord constraints, alternatives, costs, and validation for each decision.\n', 'ADR home');
  add(files, 'src/app/.gitkeep', '', 'Application composition boundary');
  add(files, 'src/shared/components/.gitkeep', '', 'Cross-domain UI primitives');
  add(files, 'src/shared/utils/.gitkeep', '', 'Pure cross-domain utilities');
  for (const area of config.core) add(files, `src/core/${area}/.gitkeep`, '', `Core ${area} boundary`);

  if (config.capabilities.includes('design-system')) {
    for (const area of ['tokens', 'theme', 'primitives', 'components', 'testing']) add(files, `src/design-system/${area}/.gitkeep`, '', 'Design system boundary');
  }
  if (config.offline.mode === 'offline-write' || config.offline.mode === 'local-first') {
    for (const file of ['outbox.ts', 'sync-engine.ts', 'conflict-policy.ts']) add(files, `src/core/sync/${file}`, marker(`Offline ${file}`), 'Offline synchronization contract');
  }
  if (config.release.provider === 'eas') {
    add(files, 'eas.json', `${JSON.stringify({ cli: { version: '>= 16.0.0' }, build: { development: { developmentClient: true, distribution: 'internal' }, preview: { distribution: 'internal', channel: 'preview' }, production: { autoIncrement: true, channel: 'production' } } }, null, 2)}\n`, 'EAS build profiles');
  } else if (config.release.provider === 'fastlane') {
    add(files, 'fastlane/Fastfile', "default_platform(:ios)\n\nplatform :ios do\n  lane :beta do\n    build_app\n    upload_to_testflight\n  end\nend\n", 'Native release automation starting point');
  }

  for (const name of config.modules) {
    const root = moduleRoot(config, name);
    for (const folder of ['api', 'model', 'routes', 'tests', ...presentationFolders(config.presentation)]) add(files, `${root}/${folder}/.gitkeep`, '', `${name} ${folder} boundary`);
    add(files, `${root}/index.ts`, marker(`Public API for ${name}`), 'Module public API');
    if (config.topology !== 'modular-monolith') add(files, `packages/module-${name}/package.json`, `${JSON.stringify({ name: `@app/module-${name}`, private: true, version: '0.0.0', type: 'module', main: './src/index.ts' }, null, 2)}\n`, 'Package boundary');
  }

  const dependencies = dependenciesFor(config);
  add(files, 'docs/architecture/dependencies.md', `# Capability dependencies\n\n${dependencies.map((d) => `- ${d}`).join('\n') || '- none'}\n\nInstall only after reviewing compatibility with the detected React Native or Expo baseline.\n`, 'Reviewed dependency plan');
  add(files, 'docs/architecture/guardrails.md', `# Guardrails\n\n${config.capabilities.flatMap((name) => CATALOG[name].guards).filter((v, i, a) => a.indexOf(v) === i).map((g) => `- ${g}`).join('\n')}\n`, 'Enforceable architecture controls');
  return { root: resolve(rootInput), config, files, warnings };
}

export function planModule(rootInput: string, config: ArchitectureConfig, name: string): ArchitecturePlan {
  return plan(rootInput, { ...config, modules: [...new Set([...config.modules, name])].sort() });
}
